//go:build js && wasm

package ttf

import (
	"runtime"
	"syscall/js"
	"unsafe"
)

var bridge js.Value

func init() {
	runtime.LockOSThread()

	bridge = js.Global().Get("sdlBridge")
	if bridge.IsUndefined() {
		panic("sdlBridge not initialized")
	}
	memoryBufferPtr := bridge.Call("getMemoryBufferPtr").Int() // JS memory buffer
	memoryBufferView := bridge.Call("getMemoryBufferView")     // Uint8Array of JS memory buffer
	_, _ = memoryBufferPtr, memoryBufferView

	// purego.RegisterLibFunc(&ttfAddFallbackFont, lib, "TTF_AddFallbackFont")
	// purego.RegisterLibFunc(&ttfAppendTextString, lib, "TTF_AppendTextString")
	// purego.RegisterLibFunc(&ttfClearFallbackFonts, lib, "TTF_ClearFallbackFonts")
	// purego.RegisterLibFunc(&ttfCloseFont, lib, "TTF_CloseFont")
	// purego.RegisterLibFunc(&ttfCopyFont, lib, "TTF_CopyFont")
	// purego.RegisterLibFunc(&ttfCreateGPUTextEngine, lib, "TTF_CreateGPUTextEngine")
	// purego.RegisterLibFunc(&ttfCreateGPUTextEngineWithProperties, lib, "TTF_CreateGPUTextEngineWithProperties")
	// purego.RegisterLibFunc(&ttfCreateRendererTextEngine, lib, "TTF_CreateRendererTextEngine")
	// purego.RegisterLibFunc(&ttfCreateRendererTextEngineWithProperties, lib, "TTF_CreateRendererTextEngineWithProperties")
	// purego.RegisterLibFunc(&ttfCreateSurfaceTextEngine, lib, "TTF_CreateSurfaceTextEngine")
	// purego.RegisterLibFunc(&ttfCreateText, lib, "TTF_CreateText")
	// purego.RegisterLibFunc(&ttfDeleteTextString, lib, "TTF_DeleteTextString")
	// purego.RegisterLibFunc(&ttfDestroyGPUTextEngine, lib, "TTF_DestroyGPUTextEngine")
	// purego.RegisterLibFunc(&ttfDestroyRendererTextEngine, lib, "TTF_DestroyRendererTextEngine")
	// purego.RegisterLibFunc(&ttfDestroySurfaceTextEngine, lib, "TTF_DestroySurfaceTextEngine")
	// purego.RegisterLibFunc(&ttfDestroyText, lib, "TTF_DestroyText")
	// purego.RegisterLibFunc(&ttfDrawRendererText, lib, "TTF_DrawRendererText")
	// purego.RegisterLibFunc(&ttfDrawSurfaceText, lib, "TTF_DrawSurfaceText")
	// purego.RegisterLibFunc(&ttfFontHasGlyph, lib, "TTF_FontHasGlyph")
	// purego.RegisterLibFunc(&ttfFontIsFixedWidth, lib, "TTF_FontIsFixedWidth")
	// purego.RegisterLibFunc(&ttfFontIsScalable, lib, "TTF_FontIsScalable")
	// purego.RegisterLibFunc(&ttfGetFontAscent, lib, "TTF_GetFontAscent")
	// purego.RegisterLibFunc(&ttfGetFontDescent, lib, "TTF_GetFontDescent")
	// purego.RegisterLibFunc(&ttfGetFontDirection, lib, "TTF_GetFontDirection")
	// purego.RegisterLibFunc(&ttfGetFontDPI, lib, "TTF_GetFontDPI")
	// purego.RegisterLibFunc(&ttfGetFontFamilyName, lib, "TTF_GetFontFamilyName")
	// purego.RegisterLibFunc(&ttfGetFontGeneration, lib, "TTF_GetFontGeneration")
	// purego.RegisterLibFunc(&ttfGetFontHeight, lib, "TTF_GetFontHeight")
	// purego.RegisterLibFunc(&ttfGetFontHinting, lib, "TTF_GetFontHinting")
	// purego.RegisterLibFunc(&ttfGetFontKerning, lib, "TTF_GetFontKerning")
	// purego.RegisterLibFunc(&ttfGetFontLineSkip, lib, "TTF_GetFontLineSkip")
	// purego.RegisterLibFunc(&ttfGetFontOutline, lib, "TTF_GetFontOutline")
	// purego.RegisterLibFunc(&ttfGetFontProperties, lib, "TTF_GetFontProperties")
	// purego.RegisterLibFunc(&ttfGetFontScript, lib, "TTF_GetFontScript")
	// purego.RegisterLibFunc(&ttfGetFontSDF, lib, "TTF_GetFontSDF")
	// purego.RegisterLibFunc(&ttfGetFontSize, lib, "TTF_GetFontSize")
	// purego.RegisterLibFunc(&ttfGetFontStyle, lib, "TTF_GetFontStyle")
	// purego.RegisterLibFunc(&ttfGetFontStyleName, lib, "TTF_GetFontStyleName")
	// purego.RegisterLibFunc(&ttfGetFontWrapAlignment, lib, "TTF_GetFontWrapAlignment")
	// purego.RegisterLibFunc(&ttfGetFreeTypeVersion, lib, "TTF_GetFreeTypeVersion")
	// purego.RegisterLibFunc(&ttfGetGlyphImage, lib, "TTF_GetGlyphImage")
	// purego.RegisterLibFunc(&ttfGetGlyphImageForIndex, lib, "TTF_GetGlyphImageForIndex")
	// purego.RegisterLibFunc(&ttfGetGlyphKerning, lib, "TTF_GetGlyphKerning")
	// purego.RegisterLibFunc(&ttfGetGlyphMetrics, lib, "TTF_GetGlyphMetrics")
	// purego.RegisterLibFunc(&ttfGetGlyphScript, lib, "TTF_GetGlyphScript")
	// purego.RegisterLibFunc(&ttfGetGPUTextDrawData, lib, "TTF_GetGPUTextDrawData")
	// purego.RegisterLibFunc(&ttfGetGPUTextEngineWinding, lib, "TTF_GetGPUTextEngineWinding")
	// purego.RegisterLibFunc(&ttfGetHarfBuzzVersion, lib, "TTF_GetHarfBuzzVersion")
	// purego.RegisterLibFunc(&ttfGetNextTextSubString, lib, "TTF_GetNextTextSubString")
	// purego.RegisterLibFunc(&ttfGetNumFontFaces, lib, "TTF_GetNumFontFaces")
	// purego.RegisterLibFunc(&ttfGetPreviousTextSubString, lib, "TTF_GetPreviousTextSubString")
	// purego.RegisterLibFunc(&ttfGetStringSize, lib, "TTF_GetStringSize")
	// purego.RegisterLibFunc(&ttfGetStringSizeWrapped, lib, "TTF_GetStringSizeWrapped")
	// purego.RegisterLibFunc(&ttfGetTextColor, lib, "TTF_GetTextColor")
	// purego.RegisterLibFunc(&ttfGetTextColorFloat, lib, "TTF_GetTextColorFloat")
	// purego.RegisterLibFunc(&ttfGetTextDirection, lib, "TTF_GetTextDirection")
	// purego.RegisterLibFunc(&ttfGetTextEngine, lib, "TTF_GetTextEngine")
	// purego.RegisterLibFunc(&ttfGetTextFont, lib, "TTF_GetTextFont")
	// purego.RegisterLibFunc(&ttfGetTextPosition, lib, "TTF_GetTextPosition")
	// purego.RegisterLibFunc(&ttfGetTextProperties, lib, "TTF_GetTextProperties")
	// purego.RegisterLibFunc(&ttfGetTextScript, lib, "TTF_GetTextScript")
	// purego.RegisterLibFunc(&ttfGetTextSize, lib, "TTF_GetTextSize")
	// purego.RegisterLibFunc(&ttfGetTextSubString, lib, "TTF_GetTextSubString")
	// purego.RegisterLibFunc(&ttfGetTextSubStringForLine, lib, "TTF_GetTextSubStringForLine")
	// purego.RegisterLibFunc(&ttfGetTextSubStringForPoint, lib, "TTF_GetTextSubStringForPoint")
	// purego.RegisterLibFunc(&ttfGetTextSubStringsForRange, lib, "TTF_GetTextSubStringsForRange")
	// purego.RegisterLibFunc(&ttfGetTextWrapWidth, lib, "TTF_GetTextWrapWidth")
	// purego.RegisterLibFunc(&ttfInit, lib, "TTF_Init")
	// purego.RegisterLibFunc(&ttfInsertTextString, lib, "TTF_InsertTextString")
	// purego.RegisterLibFunc(&ttfMeasureString, lib, "TTF_MeasureString")
	// purego.RegisterLibFunc(&ttfOpenFont, lib, "TTF_OpenFont")
	// purego.RegisterLibFunc(&ttfOpenFontIO, lib, "TTF_OpenFontIO")
	// purego.RegisterLibFunc(&ttfOpenFontWithProperties, lib, "TTF_OpenFontWithProperties")
	// purego.RegisterLibFunc(&ttfQuit, lib, "TTF_Quit")
	// purego.RegisterLibFunc(&ttfRemoveFallbackFont, lib, "TTF_RemoveFallbackFont")
	// purego.RegisterLibFunc(&ttfRenderGlyphBlended, lib, "TTF_RenderGlyph_Blended")
	// purego.RegisterLibFunc(&ttfRenderGlyphLCD, lib, "TTF_RenderGlyph_LCD")
	// purego.RegisterLibFunc(&ttfRenderGlyphShaded, lib, "TTF_RenderGlyph_Shaded")
	// purego.RegisterLibFunc(&ttfRenderGlyphSolid, lib, "TTF_RenderGlyph_Solid")
	// purego.RegisterLibFunc(&ttfRenderTextBlended, lib, "TTF_RenderText_Blended")
	// purego.RegisterLibFunc(&ttfRenderTextBlendedWrapped, lib, "TTF_RenderText_Blended_Wrapped")
	// purego.RegisterLibFunc(&ttfRenderTextLCD, lib, "TTF_RenderText_LCD")
	// purego.RegisterLibFunc(&ttfRenderTextLCDWrapped, lib, "TTF_RenderText_LCD_Wrapped")
	// purego.RegisterLibFunc(&ttfRenderTextShaded, lib, "TTF_RenderText_Shaded")
	// purego.RegisterLibFunc(&ttfRenderTextShadedWrapped, lib, "TTF_RenderText_Shaded_Wrapped")
	// purego.RegisterLibFunc(&ttfRenderTextSolid, lib, "TTF_RenderText_Solid")
	// purego.RegisterLibFunc(&ttfRenderTextSolidWrapped, lib, "TTF_RenderText_Solid_Wrapped")
	// purego.RegisterLibFunc(&ttfSetFontDirection, lib, "TTF_SetFontDirection")
	// purego.RegisterLibFunc(&ttfSetFontHinting, lib, "TTF_SetFontHinting")
	// purego.RegisterLibFunc(&ttfSetFontKerning, lib, "TTF_SetFontKerning")
	// purego.RegisterLibFunc(&ttfSetFontLanguage, lib, "TTF_SetFontLanguage")
	// purego.RegisterLibFunc(&ttfSetFontLineSkip, lib, "TTF_SetFontLineSkip")
	// purego.RegisterLibFunc(&ttfSetFontOutline, lib, "TTF_SetFontOutline")
	// purego.RegisterLibFunc(&ttfSetFontScript, lib, "TTF_SetFontScript")
	// purego.RegisterLibFunc(&ttfSetFontSDF, lib, "TTF_SetFontSDF")
	// purego.RegisterLibFunc(&ttfSetFontSize, lib, "TTF_SetFontSize")
	// purego.RegisterLibFunc(&ttfSetFontSizeDPI, lib, "TTF_SetFontSizeDPI")
	// purego.RegisterLibFunc(&ttfSetFontStyle, lib, "TTF_SetFontStyle")
	// purego.RegisterLibFunc(&ttfSetFontWrapAlignment, lib, "TTF_SetFontWrapAlignment")
	// purego.RegisterLibFunc(&ttfSetGPUTextEngineWinding, lib, "TTF_SetGPUTextEngineWinding")
	// purego.RegisterLibFunc(&ttfSetTextColor, lib, "TTF_SetTextColor")
	// purego.RegisterLibFunc(&ttfSetTextColorFloat, lib, "TTF_SetTextColorFloat")
	// purego.RegisterLibFunc(&ttfSetTextDirection, lib, "TTF_SetTextDirection")
	// purego.RegisterLibFunc(&ttfSetTextEngine, lib, "TTF_SetTextEngine")
	// purego.RegisterLibFunc(&ttfSetTextFont, lib, "TTF_SetTextFont")
	// purego.RegisterLibFunc(&ttfSetTextPosition, lib, "TTF_SetTextPosition")
	// purego.RegisterLibFunc(&ttfSetTextScript, lib, "TTF_SetTextScript")
	// purego.RegisterLibFunc(&ttfSetTextString, lib, "TTF_SetTextString")
	// purego.RegisterLibFunc(&ttfSetTextWrapWhitespaceVisible, lib, "TTF_SetTextWrapWhitespaceVisible")
	// purego.RegisterLibFunc(&ttfSetTextWrapWidth, lib, "TTF_SetTextWrapWidth")
	// purego.RegisterLibFunc(&ttfStringToTag, lib, "TTF_StringToTag")
	// purego.RegisterLibFunc(&ttfTagToString, lib, "TTF_TagToString")
	// purego.RegisterLibFunc(&ttfTextWrapWhitespaceVisible, lib, "TTF_TextWrapWhitespaceVisible")
	// purego.RegisterLibFunc(&ttfUpdateText, lib, "TTF_UpdateText")
	ttfVersion = func() int32 { return int32(bridge.Call("TTF_Version").Int()) }
	// purego.RegisterLibFunc(&ttfWasInit, lib, "TTF_WasInit")

	// Load functions available since 3.2.2
	versionMajor, versionMinor, versionPatch := Version()
	if versionMajor >= 3 && versionMinor >= 2 && versionPatch >= 2 {
		ttfGetFontWeight = func(font *Font) int32 { return int32(bridge.Call("TTF_GetFontWeight", unsafe.Pointer(font)).Int()) }
	}
}
